### ISSUE TITLE
NPCS AND VJ NPCS NOT HOLDING A GUN!!!

### ISSUE THREAD

**Issue by gmodman** [DrVrej/VJ-Base#11] opened 2018-04-21 11:21 UTC
Once I Was In Gmod I Screenshot it and look it of my picture. https://imgur.com/GJ92plH

**Comment by DrVrej** [comment] 2018-04-21 14:55
That is not from my side, you have an addon replacing CSS models, uninstall that broken mod. Once uninstalled VJ Base along with all other mods that use CSS weapons will be fixed.

**Comment by gmodman** [comment] 2018-04-22 18:43
okay!

**Comment by gmodman** [comment] 2018-04-22 20:05
i did it and it don't work

**Comment by DrVrej** [comment] 2018-04-22 20:59
Well this problem is invalid, this has nothing to do from my base. I am simply using models that come with Garry's Mod itself. So it doesn't make sense to report the model problems to me.

**Comment by gmodman** [comment] 2018-04-23 23:44
well this problem is Vaild This has NOT HOLDING GODDAM MACHINE GUN!!!!!!!!

**Comment by DrVrej** [comment] 2018-04-24 14:33
Duplicate of #12

**Closed** 2018-04-24 14:33 UTC
Labels: invalid
